server:
  port: 8720
spring:
  application:
    name: hwj-lumia-consumer
  cloud:
    config:
      profile: dev
      discovery:
        enabled: true
        service-id: hwj-lumia-config-server
      username: letrain
      password: hwj38121
      fail-fast: true
      retry:
        max-attempts: 6
        multiplier: 1.1
        initial-interval: 1000
        max-interval: 2000
  zipkin:
    base-url: http://localhost:7300
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    #过期时间 30s 不在除去
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign:
  hystrix:
    enabled: true