server:
  port: 9410
eureka:
  client:
    service-url:
      defaultZone: http://192.168.56.102:9800/eureka
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
       ## spring boot 2.0以上的版本改成 spring.cloud.client.ip-address
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: hwj-meego-provider-dev
  zipkin:
    base-url: http://192.168.56.101:9300
    enabled: true
management:
  port: 9210