server:
  port: 7420
spring:
  application:
    name: hwj-meego-consumer-test
  zipkin:
    enabled: true
    base-url: http://localhost:9300
  sleuth:
    sampler:
      percentage: 0.8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
       ## spring boot 2.0以上的版本改成 spring.cloud.client.ip-address
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 3000
        loggerLevel: full
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 1000

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
             # 是否启用执行超时机制，默认为true
             timeoutEnabled: true
             # 执行超时时间，默认为1000毫秒，
             timeoutInMilliseconds: 3000
             # 当隔离策略为THREAD时，当执行线程执行超时时，是否进行中断处理，即Future#cancel(true)处理，默认为false
             interruptOnFutureCancel: true
management:
  security:
    enabled: false  